### ISSUE TITLE
Docs can't be parsed to a variable

### ISSUE THREAD

**Issue by KFReg** [kdbinsidebrains/plugin#20]
doesn't seem to affect the IDE running, but it comes up:

IntelliJ IDEA 2021.3.2 (Community Edition)

Build #IC-213.6777.52, built on January 28, 2022

Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Unhandled exception in [StandaloneCoroutine{Cancelling}@78dbd726, EdtCoroutineDispatcher@1aa0815c]

java.lang.NullPointerException
	at org.kdb.inside.brains.lang.docs.QVariableDoc.extractDocs(QVariableDoc.java:164)
	at org.kdb.inside.brains.lang.docs.QVariableDoc.from(QVariableDoc.java:73)
	at org.kdb.inside.brains.lang.docs.QDocumentationProvider.createVariableDoc(QDocumentationProvider.java:73)
	at org.kdb.inside.brains.lang.docs.QDocumentationProvider.generateDoc(QDocumentationProvider.java:51)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:141)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:73)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:58)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt:25)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:65)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:12)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$3.run(ReadAction.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.application.rw.ReadAction.tryReadAction(ReadAction.kt:71)
	at com.intellij.openapi.application.rw.ReadAction.access$tryReadAction(ReadAction.kt:14)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2$2.run(ReadAction.kt:62)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2.invokeSuspend(ReadAction.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by smklimenko** [comment]
Resolved in 0.18.1. The version has been pushed and will be available after JetBrains' approval.
