### ISSUE TITLE
Charting IDE error in intelliJ

### ISSUE THREAD

**Issue by pdjames** [kdbinsidebrains/plugin#66]
I get an IDE error when I attempt to chart...

Steps; 
Connect to instance
Query some data
click 'Show Chart' button alongside table of returned data

I got the error initially with;

          IntelliJ IDEA 2022.2.3 (Community Edition)
          Build #IC-222.4345.14, built on October 5, 2022
          Runtime version: 17.0.4.1+7-b469.62 amd64
          VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
          Windows 10 10.0
          GC: G1 Young Generation, G1 Old Generation
          Memory: 2048M
          Cores: 6
          Non-Bundled Plugins:
              org.kdb.inside.brains.KdbInsideBrains (3.6.2)
              org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
              PythonCore (222.4345.14)
              Jetbrains TeamCity Plugin (2022.12.123334)
          
          Kotlin: 222-1.7.21-release-272-IJ4167.29

I upgraded to;

          IntelliJ IDEA 2022.2.4 (Community Edition)
          Build #IC-222.4459.24, built on November 22, 2022
          Runtime version: 17.0.5+7-b469.71 amd64
          VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
          Windows 10 10.0
          GC: G1 Young Generation, G1 Old Generation
          Memory: 2048M
          Cores: 6
          Non-Bundled Plugins:
              org.kdb.inside.brains.KdbInsideBrains (3.6.2)
              org.jetbrains.kotlin (222-1.8.10-release-430-IJ4167.29)
              PythonCore (222.4459.24)
              Jetbrains TeamCity Plugin (2022.12.123443)
          
          Kotlin: 222-1.8.10-release-430-IJ4167.29

Then I downgraded to;

          IntelliJ IDEA 2022.2 (Community Edition)
          Build #IC-222.3345.118, built on July 26, 2022
          Runtime version: 17.0.3+7-b469.32 amd64
          VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
          Windows 10 10.0
          GC: G1 Young Generation, G1 Old Generation
          Memory: 2048M
          Cores: 6
          Non-Bundled Plugins:
              org.kdb.inside.brains.KdbInsideBrains (3.6.2)
              Jetbrains TeamCity Plugin (2022.12.123443)
          
          Kotlin: 222-1.7.10-release-334-IJ3345.118

... and the error remains the same;

            java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.actionSystem.Presentation.addPropertyChangeListener(java.beans.PropertyChangeListener)" because "this.myPresentation" is null
	            at com.intellij.openapi.actionSystem.impl.ActionButton.addNotify(ActionButton.java:264)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	            at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:729)
	            at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	            at java.desktop/java.awt.Window.addNotify(Window.java:797)
	            at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
	            at com.intellij.openapi.ui.FrameWrapper$MyJFrame.addNotify(FrameWrapper.kt:330)
	            at java.desktop/java.awt.Window.show(Window.java:1059)
	            at java.desktop/java.awt.Component.show(Component.java:1749)
	            at java.desktop/java.awt.Component.setVisible(Component.java:1696)
	            at java.desktop/java.awt.Window.setVisible(Window.java:1042)
	            at com.intellij.openapi.ui.FrameWrapper.show(FrameWrapper.kt:187)
	            at com.intellij.openapi.ui.FrameWrapper.show(FrameWrapper.kt:87)
	            at org.kdb.inside.brains.view.chart.ShowChartAction.actionPerformed(ShowChartAction.java:42)
	            at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	            at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:294)
	            at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	            at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:294)
	            at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:515)
	            at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:232)
	            at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$1(ActionPopupStep.java:220)
	            at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	            at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	            at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1543)
	            at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:113)
	            at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:180)
	            at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:133)
	            at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:164)
	            at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1540)
	            at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
	            at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
	            at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:266)
	            at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:126)
	            at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:158)
	            at com.intellij.openapi.util.Disposer.dispose(Disposer.java:217)
	            at com.intellij.openapi.util.Disposer.dispose(Disposer.java:205)
	            at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:266)
	            at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:434)
	            at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:406)
	            at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:361)
	            at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:278)
	            at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:618)
	            at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	            at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	            at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	            at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:694)
	            at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	            at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	            at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	            at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	            at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	            at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	            at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	            at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	            at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	            at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	            at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	            at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	            at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	            at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	            at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	            at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	            at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	            at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	            at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	            at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	            at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	            at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	            at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	            at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	            at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	            at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	            at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	            at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	            at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	            at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	            at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	            at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	            at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	            at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	            at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	            at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	            at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	            at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	            at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by pdjames** [comment]
Thanks
