### ISSUE TITLE
Creating new connection from 'Search Everywhere' causes NullPointerException

### ISSUE THREAD

**Issue by 75tpus** [kdbinsidebrains/plugin#89]
Fresh idea install (version 2022.3.2),  newly setup plugin  (tried 5.1 and 4.0)

The kdb settings appear in the settings dialog but no KDB windows in the View->Tool Windows menu

Idea log fragment:

00:00,300 [  65917] SEVERE - #c.i.o.a.i.FlushQueue - Cannot invoke "java.awt.event.InputEvent.getComponent()" because the return value of "com.intellij.openapi.actionSystem.AnActionEvent.getInputEvent()" is null

**java.lang.NullPointerException**: Cannot invoke "java.awt.event.InputEvent.getComponent()" because the return value of "com.intellij.openapi.actionSystem.AnActionEvent.getInputEvent()" is null

                at org.kdb.inside.brains.action.CreateConnectionAction.actionPerformed(CreateConnectionAction.java:25)

                at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)

                at com.intellij.ide.actions.GotoActionAction.lambda$performActionImpl$4(GotoActionAction.java:91)

                at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)

                at com.intellij.ide.actions.GotoActionAction.performActionImpl(GotoActionAction.java:90)

                at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:70)

                at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)

                at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)

                at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)

                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)

                at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)

                at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)

                at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)

                at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)

                at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)

                at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)

                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)

                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)

                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)

                at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)

                at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)

                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)

                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)

                at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)

                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)

                at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)

                at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)

                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)

                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)

                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)

                at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)

                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)

                at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)

                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)

                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)

                at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

2024-01-03 17:00:00,303 [  65920] SEVERE - #c.i.o.a.i.FlushQueue - IntelliJ IDEA 2022.3.2  Build #IC-223.8617.56

2024-01-03 17:00:00,303 [  65920] SEVERE - #c.i.o.a.i.FlushQueue - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.

2024-01-03 17:00:00,303 [  65920] SEVERE - #c.i.o.a.i.FlushQueue - OS: Windows 10

2024-01-03 17:00:00,303 [  65920] SEVERE - #c.i.o.a.i.FlushQueue - **Plugin to blame: KdbInsideBrains version: 4.0.0**

**Comment by smklimenko** [comment]
great, thanks for the report. There is definitely something wrong in this part, but it shouldn't affect the plugin functionality. 

As you use IntelliJ IDEA, all tool windows will be shown only when Q language is enabled for a module as described here: https://www.kdbinsidebrains.dev/project/module#add-framework. Have you added the Q framework to any your module in the project?

**Comment by 75tpus** [comment]
aagh makes sense!! will try that

many thanks!
