### ISSUE TITLE
floating point precision Exception in plugin (5.5.0)

### ISSUE THREAD

**Issue by maxpaton** [kdbinsidebrains/plugin#96]
Hi there,

I have encountered an Exception error in your plugin, which occurs when the floating point precision is set to the maximum precision (16). This is the error I receive whenever I display a table result with floats in it, and my colleague does too:

java.lang.NullPointerException: Cannot invoke "java.text.DecimalFormat.format(double)" because "formats[java.math.RoundingMode.ordinal()][org.kdb.inside.brains.view.FormatterOptions.getFloatPrecision()]" is null
	at org.kdb.inside.brains.view.KdbOutputFormatter.doubleToStr(KdbOutputFormatter.java:696)
	at org.kdb.inside.brains.view.KdbOutputFormatter.formatDouble(KdbOutputFormatter.java:678)
	at org.kdb.inside.brains.view.KdbOutputFormatter.formatObject(KdbOutputFormatter.java:154)
	at org.kdb.inside.brains.view.KdbOutputFormatter.objectToString(KdbOutputFormatter.java:75)
	at org.kdb.inside.brains.view.KdbOutputFormatter.objectToString(KdbOutputFormatter.java:64)
	at org.kdb.inside.brains.view.console.table.TableResultView$7.setValue(TableResultView.java:328)
	at java.desktop/javax.swing.table.DefaultTableCellRenderer.getTableCellRendererComponent(DefaultTableCellRenderer.java:262)
	at org.kdb.inside.brains.view.console.table.TableResultView$7.getTableCellRendererComponent(TableResultView.java:277)
	at com.intellij.ui.table.JBTable.calculateRowHeight(JBTable.java:264)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:242)
	at java.desktop/javax.swing.JTable.getRowHeight(JTable.java:1065)
	at java.desktop/javax.swing.JTable.getCellRect(JTable.java:2984)
	at com.intellij.ui.table.JBTable.getPreferredScrollableViewportSize(JBTable.java:361)
	at com.intellij.ui.components.JBViewport.getPreferredScrollableViewportSize(JBViewport.java:522)
	at com.intellij.ui.components.JBViewport$1.preferredLayoutSize(JBViewport.java:65)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.ui.components.JBScrollPane$Layout.preferredLayoutSize(JBScrollPane.java:821)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.openapi.ui.Splitter.getPreferredSize(Splitter.java:272)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.ui.components.panels.Wrapper.getPreferredSize(Wrapper.java:115)
	at com.intellij.ui.tabs.impl.JBTabsImpl$getPreferredSize$1.invoke(JBTabsImpl.kt:2117)
	at com.intellij.ui.tabs.impl.JBTabsImpl$getPreferredSize$1.invoke(JBTabsImpl.kt:2116)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getPreferredSize$lambda$24(JBTabsImpl.kt:2117)
	at com.intellij.ui.tabs.impl.JBTabsImpl.computeSize(JBTabsImpl.kt:2125)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getPreferredSize(JBTabsImpl.kt:2116)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.actionsUpdated(ActionToolbarImpl.java:1453)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1391)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:234)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:178)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:81)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsWithoutLoadingIcon(ActionToolbarImpl.java:1355)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1349)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1326)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsOnAdd(ActionToolbarImpl.java:356)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:350)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4840)
	at java.desktop/java.awt.Container.lambda$addImpl$0(Container.java:1150)
	at java.desktop/sun.awt.SunToolkit.lambda$performWithTreeLock$1(SunToolkit.java:2145)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2170)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2143)
	at java.desktop/java.awt.Container.addImpl(Container.java:1104)
	at com.intellij.ui.tabs.impl.JBTabsImpl.addImpl(JBTabsImpl.kt:2442)
	at java.desktop/java.awt.Container.add(Container.java:440)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateContainer(JBTabsImpl.kt:2352)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.kt:1312)
	at com.intellij.ui.tabs.impl.JBTabsImpl.doSetSelected(JBTabsImpl.kt:1276)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.kt:1258)
	at org.kdb.inside.brains.view.console.table.TabsTableResult.insertNewTab(TabsTableResult.java:296)
	at org.kdb.inside.brains.view.console.table.TabsTableResult.updateTableResult(TabsTableResult.java:340)
	at org.kdb.inside.brains.view.console.KdbConsolePanel.lambda$processQuery$1(KdbConsolePanel.java:550)
	at org.kdb.inside.brains.core.KdbConnectionManager$TheInstanceConnection.lambda$doQuery$0(KdbConnectionManager.java:610)
	at org.kdb.inside.brains.core.KdbConnectionManager$TheInstanceConnection$5.onFinished(KdbConnectionManager.java:638)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:172)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:499)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

I thought I would make you aware of it and hopefully to fix it if possible.

Thanks,
Max

**Comment by smklimenko** [comment]
fixed in Version 5.5.1 once approve by JetBrains
